name: Generate Podcast Feeds
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run feed generator
        uses: ifarshgar/github-actions-course-generator@main
          
